### ISSUE TITLE
Under Account Linking, Client ID is not available.

### ISSUE THREAD

**Issue by ssethi-hub** [actions-on-google/dialogflow-google-sign-in-nodejs#3]
In Configuration -> Actions Console
Step 2 - From the top navigation menu under Develop > Account linking (left nav):
Account creation > select Yes, allow users to sign up for new accounts via voice.
Linking type > select Google Sign In.
Client information > copy Client ID > Save.

Instead of Client ID, two blank fields "Authorization URL" and "Token URL" are visible. I double checked that Linking type is Google Sign In.

**Comment by binod-regmi** [comment]
i am also having the same problem

**Comment by Fleker** [comment]
We're aware of this.

**Comment by ssethi-hub** [comment]
I now see that it is working as expected.
